"""
Pydantic Schemas Package for BharatTrip SSOT (Updated with Milestone 3 Schemas).
"""
from backend.app.schemas.support import (
    SupportTicketBase,
    SupportTicketCreate,
    SupportTicketUpdate,
    SupportTicketResponse,
    SupportTicketListResponse,
)
from backend.app.schemas.finance import (
    FinanceRecordBase,
    FinanceRecordCreate,
    FinanceRecordUpdate,
    FinanceRecordResponse,
    FinanceRecordListResponse,
)
from backend.app.schemas.escalation import (
    EscalationBase,
    EscalationCreate,
    EscalationUpdate,
    EscalationResponse,
    EscalationListResponse,
)
from backend.app.schemas.audit import (
    AuditLogBase,
    AuditLogCreate,
    AuditLogResponse,
    AuditLogListResponse,
)
from backend.app.schemas.auth import (
    MockLoginRequest,
    LoginRequest,
    UserProfile,
    TokenResponse,
    RefreshTokenRequest,
)
from backend.app.schemas.reconciliation import (
    RiskLevelEnum,
    MismatchStatusEnum,
    ResolutionTypeEnum,
    MismatchItem,
    MismatchListResponse,
    OrphanTicketItem,
    OrphanResponse,
    ReconciliationSummary,
    ResolveMismatchRequest,
    ResolveMismatchResponse,
    BatchResolveMismatchesRequest,
    BatchResolveMismatchesResponse,
    AIEntityResolutionMatch,
    AIEntityResolutionRequest,
    AIEntityResolutionResponse,
    DraftReconciliationMessageRequest,
    DraftReconciliationMessageResponse,
)
from backend.app.schemas.metrics import (
    WindowFilterEnum,
    SLARiskLevelEnum,
    DashboardMetricsResponse,
    RCAMetricsResponse,
    TrendDataPoint,
    TrendsResponse,
    SLABreachItem,
    SLABreachResponse,
    CarrierPerformanceItem,
    CarrierPerformanceResponse,
)
from backend.app.schemas.partners import (
    RevenueTierEnum,
    PartnerRiskStatusEnum,
    UrgencyLevelEnum,
    PriorityRankEnum,
    PartnerHealthItem,
    PartnerMatrixResponse,
    PartnerSentimentAnalysisRequest,
    PartnerSentimentAnalysisResponse,
    PartnerOutreachRequest,
    PartnerOutreachResponse,
    PolicyRuleResponse,
    PolicyRuleListResponse,
    PolicyRuleLookupRequest,
)

__all__ = [
    # Support
    "SupportTicketBase",
    "SupportTicketCreate",
    "SupportTicketUpdate",
    "SupportTicketResponse",
    "SupportTicketListResponse",
    # Finance
    "FinanceRecordBase",
    "FinanceRecordCreate",
    "FinanceRecordUpdate",
    "FinanceRecordResponse",
    "FinanceRecordListResponse",
    # Escalations
    "EscalationBase",
    "EscalationCreate",
    "EscalationUpdate",
    "EscalationResponse",
    "EscalationListResponse",
    # Audit
    "AuditLogBase",
    "AuditLogCreate",
    "AuditLogResponse",
    "AuditLogListResponse",
    # Auth
    "MockLoginRequest",
    "LoginRequest",
    "UserProfile",
    "TokenResponse",
    "RefreshTokenRequest",
    # Reconciliation (M3)
    "RiskLevelEnum",
    "MismatchStatusEnum",
    "ResolutionTypeEnum",
    "MismatchItem",
    "MismatchListResponse",
    "OrphanTicketItem",
    "OrphanResponse",
    "ReconciliationSummary",
    "ResolveMismatchRequest",
    "ResolveMismatchResponse",
    "BatchResolveMismatchesRequest",
    "BatchResolveMismatchesResponse",
    "AIEntityResolutionMatch",
    "AIEntityResolutionRequest",
    "AIEntityResolutionResponse",
    "DraftReconciliationMessageRequest",
    "DraftReconciliationMessageResponse",
    # Metrics (M3)
    "WindowFilterEnum",
    "SLARiskLevelEnum",
    "DashboardMetricsResponse",
    "RCAMetricsResponse",
    "TrendDataPoint",
    "TrendsResponse",
    "SLABreachItem",
    "SLABreachResponse",
    "CarrierPerformanceItem",
    "CarrierPerformanceResponse",
    # Partners & Policy (M3)
    "RevenueTierEnum",
    "PartnerRiskStatusEnum",
    "UrgencyLevelEnum",
    "PriorityRankEnum",
    "PartnerHealthItem",
    "PartnerMatrixResponse",
    "PartnerSentimentAnalysisRequest",
    "PartnerSentimentAnalysisResponse",
    "PartnerOutreachRequest",
    "PartnerOutreachResponse",
    "PolicyRuleResponse",
    "PolicyRuleListResponse",
    "PolicyRuleLookupRequest",
]
