"""
Pydantic Schemas Package for BharatTrip SSOT.
"""
from backend.app.schemas.support import (
    SupportTicketBase,
    SupportTicketCreate,
    SupportTicketUpdate,
    SupportTicketResponse,
    SupportTicketListResponse,
)
from backend.app.schemas.finance import (
    FinanceRecordBase,
    FinanceRecordCreate,
    FinanceRecordUpdate,
    FinanceRecordResponse,
    FinanceRecordListResponse,
)
from backend.app.schemas.escalation import (
    EscalationBase,
    EscalationCreate,
    EscalationUpdate,
    EscalationResponse,
    EscalationListResponse,
)
from backend.app.schemas.audit import (
    AuditLogBase,
    AuditLogCreate,
    AuditLogResponse,
    AuditLogListResponse,
)
from backend.app.schemas.auth import (
    MockLoginRequest,
    LoginRequest,
    UserProfile,
    TokenResponse,
    RefreshTokenRequest,
)
from backend.app.schemas.reconciliation import (
    MismatchItem,
    MismatchListResponse,
    OrphanTicketItem,
    OrphanResponse,
    ReconciliationSummary,
    ResolveMismatchRequest,
    ResolveMismatchResponse,
    LinkOrphanRequest,
    LinkOrphanResponse,
    BatchResolveMismatchesRequest,
    BatchResolveMismatchesResponse,
    AIEntityResolutionMatch,
    AIEntityResolutionRequest,
    AIEntityResolutionResponse,
    DraftExplanationRequest,
    DraftExplanationResponse,
    DraftReconciliationMessageRequest,
    DraftReconciliationMessageResponse,
    ProactiveNotificationRequest,
    ProactiveNotificationResponse,
)
from backend.app.schemas.metrics import (
    DashboardSummary,
    CorridorNode,
    MonthlyTrendItem,
    RootCauseItem,
    ParetoItem,
    CarrierHealthItem,
    DashboardMetricsResponse,
    RCAMetricsResponse,
    RCASynthesisResponse,
    TrendDataPoint,
    TrendsResponse,
    SLABreachItem,
    SLABreachResponse,
    CarrierPerformanceItem,
    CarrierPerformanceResponse,
)
from backend.app.schemas.partners import (
    FleetSummary,
    PartnerHealthItem,
    PartnerMatrixResponse,
    PartnerDetailResponse,
    PartnerSentimentAnalysisRequest,
    PartnerSentimentAnalysisResponse,
    PartnerOutreachRequest,
    PartnerOutreachResponse,
    PolicyRuleResponse,
    AirlinePolicyResponse,
    PolicyRuleListResponse,
    PolicyRuleLookupRequest,
    PredictSLABreachRequest,
    PredictSLABreachResponse,
)

__all__ = [
    # Support
    "SupportTicketBase",
    "SupportTicketCreate",
    "SupportTicketUpdate",
    "SupportTicketResponse",
    "SupportTicketListResponse",
    # Finance
    "FinanceRecordBase",
    "FinanceRecordCreate",
    "FinanceRecordUpdate",
    "FinanceRecordResponse",
    "FinanceRecordListResponse",
    # Escalations
    "EscalationBase",
    "EscalationCreate",
    "EscalationUpdate",
    "EscalationResponse",
    "EscalationListResponse",
    # Audit
    "AuditLogBase",
    "AuditLogCreate",
    "AuditLogResponse",
    "AuditLogListResponse",
    # Auth
    "MockLoginRequest",
    "LoginRequest",
    "UserProfile",
    "TokenResponse",
    "RefreshTokenRequest",
    # Reconciliation
    "MismatchItem",
    "MismatchListResponse",
    "OrphanTicketItem",
    "OrphanResponse",
    "ReconciliationSummary",
    "ResolveMismatchRequest",
    "ResolveMismatchResponse",
    "LinkOrphanRequest",
    "LinkOrphanResponse",
    "BatchResolveMismatchesRequest",
    "BatchResolveMismatchesResponse",
    "AIEntityResolutionMatch",
    "AIEntityResolutionRequest",
    "AIEntityResolutionResponse",
    "DraftExplanationRequest",
    "DraftExplanationResponse",
    "DraftReconciliationMessageRequest",
    "DraftReconciliationMessageResponse",
    "ProactiveNotificationRequest",
    "ProactiveNotificationResponse",
    # Metrics
    "DashboardSummary",
    "CorridorNode",
    "MonthlyTrendItem",
    "RootCauseItem",
    "ParetoItem",
    "CarrierHealthItem",
    "DashboardMetricsResponse",
    "RCAMetricsResponse",
    "RCASynthesisResponse",
    "TrendDataPoint",
    "TrendsResponse",
    "SLABreachItem",
    "SLABreachResponse",
    "CarrierPerformanceItem",
    "CarrierPerformanceResponse",
    # Partners
    "FleetSummary",
    "PartnerHealthItem",
    "PartnerMatrixResponse",
    "PartnerDetailResponse",
    "PartnerSentimentAnalysisRequest",
    "PartnerSentimentAnalysisResponse",
    "PartnerOutreachRequest",
    "PartnerOutreachResponse",
    "PolicyRuleResponse",
    "AirlinePolicyResponse",
    "PolicyRuleListResponse",
    "PolicyRuleLookupRequest",
    "PredictSLABreachRequest",
    "PredictSLABreachResponse",
]
